name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: liberica
          cache: maven
      - name: "Maven - Build Package"
        run: mvn -V -DskipTests=true install
      - name: "Maven - Test Package"
        run: mvn verify
